In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

In [2]:
X = torch.Tensor(2,3) #Tensor = 다차원 array

In [3]:
X

tensor([[-1.3956e-34,  4.5785e-41, -1.1983e-14],
        [ 4.5783e-41, -1.2026e-14,  4.5783e-41]])

In [4]:
X = torch.Tensor([[1,2,3],[4,5,6]])

In [5]:
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
x = torch.tensor(data=[2.0,3.0], requires_grad=True)
y=x**2
z = 2*y +3

target = torch.tensor([3,4])
loss = torch.sum(torch.abs(z-target))
loss.backward()

print(x.grad, y.grad, z.grad)

tensor([ 8., 12.]) None None


/tmp/ipykernel_23/3005154689.py:9: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /usr/local/src/pytorch/build/aten/src/ATen/core/TensorBody.h:486.)
  print(x.grad, y.grad, z.grad)


In [7]:
num_data = 1000
num_epoch = 500

x=init.uniform(torch.Tensor(num_data,1),-10,10)
noise = init.normal_(torch.FloatTensor(num_data,1),std=1)
y=2*x+3
y_noise = y + noise

/tmp/ipykernel_23/880071881.py:4: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  x=init.uniform(torch.Tensor(num_data,1),-10,10)


In [8]:
model = nn.Linear(1,1)
loss_func = nn.L1Loss()

In [9]:
optimizer = optim.SGD(model.parameters(),lr=0.01)

In [10]:
label = y_noise
for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)
    
    loss = loss_func(output, label)
    loss.backward()#기울기계산
    optimizer.step()#경사하강법 적용해서 기울기변경
    
    if i%10 ==0:
        print(loss.data)


tensor(10.1744)
tensor(7.6767)
tensor(5.2643)
tensor(3.1343)
tensor(2.2105)
tensor(1.9906)
tensor(1.8707)
tensor(1.7678)
tensor(1.6794)
tensor(1.5978)
tensor(1.5202)
tensor(1.4468)
tensor(1.3787)
tensor(1.3139)
tensor(1.2534)
tensor(1.1977)
tensor(1.1474)
tensor(1.1019)
tensor(1.0614)
tensor(1.0256)
tensor(0.9940)
tensor(0.9664)
tensor(0.9429)
tensor(0.9221)
tensor(0.9041)
tensor(0.8888)
tensor(0.8756)
tensor(0.8642)
tensor(0.8545)
tensor(0.8462)
tensor(0.8393)
tensor(0.8334)
tensor(0.8286)
tensor(0.8245)
tensor(0.8209)
tensor(0.8173)
tensor(0.8140)
tensor(0.8113)
tensor(0.8089)
tensor(0.8069)
tensor(0.8051)
tensor(0.8036)
tensor(0.8024)
tensor(0.8013)
tensor(0.8003)
tensor(0.7995)
tensor(0.7987)
tensor(0.7980)
tensor(0.7974)
tensor(0.7969)


In [11]:
param_list = list(model.parameters())

In [12]:
print(param_list[0].item(),param_list[1].item())

1.9885910749435425 2.8769168853759766
